# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22 * * *'
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: download file
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python3 ./preset_files.py
        
    - name: stock-info-up-to-date
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: stock-info-up-to-date
    
